platform:
  - x64

environment:
    DISCOGS_CLIENT_KEY:
      secure: SBsosj2ScnrHyUEYqEdcgdiTkf4Ol26GcibU0s1/sEU=
    DISCOGS_CLIENT_SECRET:
      secure: 5A5HsULz0KE/fBxQbYNV4CALK8hdp210Z1KT7dZmR4wPrJtT3gEHR0fWvexJiEuk
    DISCOGS_USER_AGENT:
      secure: aCqh76lO4yt6Ct5H+jRiPlP0oaY3S9kgHxd+DWidPgg=
    RUST_THREADS: 1
    global:
        PROJECT_NAME: discogs-rs
    matrix:
      - TOOLCHAIN_VERSION: 14.0
        RUST: stable
      - TOOLCHAIN_VERSION: 14.0
        RUST: beta
      - TOOLCHAIN_VERSION: 14.0
        RUST: nightly


install:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %TARGET% --default-toolchain nightly
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;C:\Users\appveyor\.rustup\toolchains\nightly-%TARGET%\bin
    - rustc -V
    - cargo -V

build: false

test_script:
    - cargo build
    - cargo test --test real_world_tests
