language: rust
matrix:
    fast_finish: true
    include:
    - rust: nightly
      env: TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
    - rust: beta
    - rust: stable
addons:
    apt:
        packages:
        - libcurl4-openssl-dev
        - libelf-dev
        - libdw-dev

before_script:
    - |
        pip install 'travis-cargo<0.2' --user &&
        export PATH=$HOME/.local/bin:$PATH

script:
    - cargo build --verbose
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
           travis-cargo test -- --lib &&
           travis-cargo test -- --doc;
      fi

    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
           travis-cargo test;
      fi

    - travis-cargo bench;
    - travis-cargo --only stable doc

after_success:
    - travis-cargo --only stable doc-upload
    - travis-cargo coveralls --no-sudo --verify

env:
    global:
        - secure: fJPG5Ssu91iymoWgrphYePS+/S8DRuigKrcdhCKNFE5PS5xzz7jZenj187AhuXRNdOZWSGTMouR4kLHK6b1LHWZO12FbhJSkgj4DwfwUVyAT8UNYmhMZjP5lyxjvNkYO0qmbM0vqk+JUBmLJ5QM5e32kZJHSox13YFWHB7BzfABLfxaWG7AO044g6K1u327w/Vpp0n9izm1yP7TUs7BJMg0Y6URt/wKfH/T+r2H+9jJ8ixK25+66UsJCeV6dAHQJ3A3JJkrklRDcsbK5WoH4Jns7uGToexj73rGscDOiHvwQTITlkGcZ2vvLNv9qIJJFnLvfrgNiu57bL2TGNM8uiX52rkGpuTGU6RV8xxBfPNT7Zaxiu9aydXFH2gM20V7s8OgQytDnUtriJnozmr35gWgeLlYgm2buIkFigMVQSbj+oQEMEp8K9mA0iBMkewyYVbw04D1bvSBtyqOLSKNZbb21WAw2sSgyEe/O4RoDlCp70uEgufT6+VcK/a8hwigJoVCVMKSUsAydYOERXSYWZzCQvPV5penCys2XLk1lGCxm1rxhgcP7c5ywIq4X60u9DOSLOHGNT44ChBjbroyPX6b5DV/PKWqEKpV4hK2PQXvuMTm9dOBm7LFSYyAftiOCLOFMy5fgd7PA+aO/PbnoVp/CAZwUqWenfd0n3fB96+k=
        - secure: W5eC1Lf0Etd0Zs7ow2vGoOM6KP4BC+5OqkUM+OvquJ5mR/AlbAfeQvMvceDxnhZnarDVJmWi1oigqWb3qsdRD1scFu43igTJQ7mH69b+8k0XLZjhI54FyEsa+NoE+12O5ES5W4HPfKO51G9aoNNpPzfjqt78qkf13KtVTWiwuvKmuZlS/x8MgbA+4ihkt4gJi4VSoWzy7JE4+3iOC4WeWKlEuDa+mrzb1XrihCnFue+wAXQQtq0KV4EPz0QksZThJdHhsiS0jcSBOaMfTAAP+Pc6H+04W3oOFNPeeuNSTY1O2lyO5tOylzvxb8oZzz5PPDIopiqAJnX3Qocw+L4w+kBs0XJA5Q5vzc+2ZfqEi1jATZ+KQOgBVZQoxwhP7rVDAQWpA5zTEKHzXmKbLaSWMaAFgVZp1ZGSoG+RUccfW/SXuFx5i8rkWbOh6Dr1mgdLiOaX9aB3fp9PURsSNnnp4rBULDqO1Xb6tR1Af4zlssphOyBZvTBz2QqIjW3z8ADIhx3F/QICRKhMzG206G4AorHBaH2m8/de/BwaTy96AoCvbQfx4HXACabhMaKt4aYjp9qW9Z3L6kMgLh2oTw8tp5OBN7mdR6aDT0I5f+6g0HUEv1dXMFi+ujGJiIPP+uqkhpYz0GblO5Nt+XLp6w/7Jyhvp3QfeliiVeS1pHR5JCE=
        - secure: cCpJC5sw+ZIiA75n9y56lGqFJfwOv17iERszCUln72Kt84sKjdxlgzNsKhMcSMex9gidOuOkxlWVxp7fui8dXONDLAj9HlVlwaP+l9vG+JObbPtfUIQ5X/NVW9lP/z4yPzBTMQ+uiQ4n7p20ZlEKUY5QE0ziPk8WO6ZEft5UtgdPwJouvT3L9vZlRgSIaPpK0C/nLZFrAfetsvYH7u71dDCmEnpJi9ymxXY3eENAUZmim34yaK2u1ewjing3HJerpavDjshix63CZA4BcerMvy5BZq+/WA4KP9mc5B4SRqiAlxHFwst1AVgB3KiehZ2A6PZ5jiB5C5seDbfoKC8ToYHEoqqiMNda6cAZjaUhbSp/N96MxO6wR9CiaWiu4yUosi1f9ZI2RRKGgjUL17j6zr8dXOlvroTW9qqq970KIPwefklFKdjyEKD9AU6kagrSPGbLzR1zAXYY1gv4zB24jfQfzjEK4DqTSIGrzsY1p9Q6NAPNDqduwhjf55N4vq4stS4m2p6COY4m7rJG/xjHfm+sgEaxDd0PiaHJxbxcaN69LvH9oznXARQCRYjZT9TvZuyC64IXOmKcpqQ4RVB5N27TAB/4lXJewTRjAA8XLVOnWHbiy+vLkkjRKXKCqLht6iY0DPHg2HVV9D2+ioKyzQKvgJn/hIeg/Qv2L/qhTfk=
        - secure: lTd90nDRtj9bNdWQxG7N95No5ah7jSmRI5rZStVvSGk0r6kVd4U5WwCKHaDo4SHVzndsiwsNfKzuyKe4QaaddwMKk1HsVRlSz/mVs5lucI4wOyZA/9At+Wk2ybF7Te1LkOMLCKZfDXH3EmSK+9nDcBfuWCdzzq0QdIpLPDJ686Jkw4jY1WSXTrVujekwgrj0BW0Xo2UNSpaT+LO+wugbel1S57R4ZfabOSdAO980OgRtdrd4GgcBe7GtDmfJwHnW7IIZgf34lp6EL4z4mO0ksXS9zrq0yUWg6MoEZZCviu+bc4qi123VuQQzAfaJd3ZjrSm5NiUCr9tol6Wh9vQO0Yabgd02hvfqPNjEaJUQmTiXKlskOpd3kT5h47PgQ/wZ2cGezjKGOp7XLWrk5Z2iAyAFayAjjq3Yqxs2cY86EKiCNnO/iIBnBeALtoMeH+FqUUAw3isxWI3fQhtWfLcQ+tIGXFlsTxsIfX6NUP+FKzs22xuD977HQh03H5VlZh5/YoR3KLhsBKX+cyP6mS/a/bV6ZTGtTi347sPB+hwe/X25s26q/SskactUDC5WbqGctNVbHQt9F7614mDDwlDEtL/ZUwNqoIyWgfFNwDDcHHcC/NVCT+Gmvs1I2sqXCAUdcnnDTIsjWz8pSR365CtoMY2VbchRnyWH+5Jc3Mbfp0g=
