platform:
  - Win32
  - x64

environment:
    global:
        PROJECT_NAME: discogs-rs
    matrix:
      - TOOLCHAIN_VERSION: 14.0
        RUST: stable
      - TOOLCHAIN_VERSION: 14.0
        RUST: beta
      - TOOLCHAIN_VERSION: 14.0
        RUST: nightly


install:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %TARGET% --default-toolchain nightly
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;C:\Users\appveyor\.rustup\toolchains\nightly-%TARGET%\bin
    - rustc -V
    - cargo -V

build: false

test_script:
    - cargo build --features debugging
    - cargo test --features debugging
    - copy target\debug\cargo-clippy.exe C:\Users\appveyor\.cargo\bin\
    - cargo clippy -- -D clippy
    - cd clippy_lints && cargo clippy -- -D clippy && cd ..

notifications:
    - provider: Email
on_build_success: false
